//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTokenAuthentication.UniversalServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniversalServiceReference1.IService1", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionMOTOR", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionMOTORResponse")]
        string commBRIDGEFusionMOTOR(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionMOTOR", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionMOTORResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionMOTORAsync(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionHEALTH", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionHEALTHResponse")]
        string commBRIDGEFusionHEALTH(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionHEALTH", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionHEALTHResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionHEALTHAsync(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionTravel", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionTravelResponse")]
        string commBRIDGEFusionTravel(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionTravel", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionTravelResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionTravelAsync(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionIPA", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionIPAResponse")]
        string commBRIDGEFusionIPA(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionIPA", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionIPAResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionIPAAsync(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionCPA", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionCPAResponse")]
        string commBRIDGEFusionCPA(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionCPA", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionCPAResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionCPAAsync(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionWC", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionWCResponse")]
        string commBRIDGEFusionWC(string strXdoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/commBRIDGEFusionWC", ReplyAction="http://tempuri.org/IService1/commBRIDGEFusionWCResponse")]
        System.Threading.Tasks.Task<string> commBRIDGEFusionWCAsync(string strXdoc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApiTokenAuthentication.UniversalServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApiTokenAuthentication.UniversalServiceReference1.IService1>, WebApiTokenAuthentication.UniversalServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string commBRIDGEFusionMOTOR(string strXdoc) {
            return base.Channel.commBRIDGEFusionMOTOR(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionMOTORAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionMOTORAsync(strXdoc);
        }
        
        public string commBRIDGEFusionHEALTH(string strXdoc) {
            return base.Channel.commBRIDGEFusionHEALTH(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionHEALTHAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionHEALTHAsync(strXdoc);
        }
        
        public string commBRIDGEFusionTravel(string strXdoc) {
            return base.Channel.commBRIDGEFusionTravel(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionTravelAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionTravelAsync(strXdoc);
        }
        
        public string commBRIDGEFusionIPA(string strXdoc) {
            return base.Channel.commBRIDGEFusionIPA(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionIPAAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionIPAAsync(strXdoc);
        }
        
        public string commBRIDGEFusionCPA(string strXdoc) {
            return base.Channel.commBRIDGEFusionCPA(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionCPAAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionCPAAsync(strXdoc);
        }
        
        public string commBRIDGEFusionWC(string strXdoc) {
            return base.Channel.commBRIDGEFusionWC(strXdoc);
        }
        
        public System.Threading.Tasks.Task<string> commBRIDGEFusionWCAsync(string strXdoc) {
            return base.Channel.commBRIDGEFusionWCAsync(strXdoc);
        }
    }
}
